/* esto es un ejemplo */

INSERT INTO PROVINCIAS(COD_PROVINCIA, PREFIJO_PROVINCIA, DESCRIPCION_PROVINCIA)
SELECT P.PROVINCIA, P.PREFIJO, P.DESCRIPCION
FROM ALMACEN1.PROVINCIAS P
-- WHERE P.PROVINCIA != 20 AND P.PROVINCIA != 28
/

INSERT INTO PROVEEDORES(COD_PROVEEDOR, NOMBRE_EMPRESA, DIRECCION, POBLACION, TELEFONO, COD_PROVINCIA)
SELECT P.PROVEEDOR, P.EMPRESA, P.DIRECCION1, P.POBLACION, P.TELEFONO, P.PROVINCIA
FROM ALMACEN1.PROVEEDORES P
WHERE P.PROVEEDOR != 101
-- WHERE P.PROVEEDOR != 127 AND P.PROVEEDOR != 148 AND P.PROVEEDOR != 101
/

INSERT INTO MEDIDAS(COD_UNIDAD_MEDIDA, DESCRIPCION_UNIDAD_MEDIDA)
SELECT DECODE(UPPER(U.UNIDAD), 'UN', TO_CHAR(1), 'M', TO_CHAR(2), 'CJ', TO_CHAR(4), 'L', TO_CHAR(5), 'CC', TO_CHAR(6), 'NO PREVISTO'), U.DESCRIPCION
FROM ALMACEN1.UNIDADES U
WHERE UPPER(U.UNIDAD) != 'KG'
/

INSERT INTO DESCUENTOS
VALUES('HABITUAL', 0)
/

/* falla por el check del stock */
INSERT INTO ARTICULOS(COD_ARTICULO, TIPO_ARTICULO, DESCRIPCION_ARTICULO, PRECIO_VENTA, STOCK, STOCK_MINIMO, COD_UNIDAD_MEDIDA)
SELECT A.ARTICULO, 'HABITUAL' TIPO, A.DESCRIPCION, A.PR_VENT, A.EXISTENCIAS, A.BAJO_MINIMO, 1
FROM ALMACEN1.ARTICULOS A
WHERE A.EXISTENCIAS > A.BAJO_MINIMO AND A.ARTICULO BETWEEN 1 AND 155 AND A.ARTICULO BETWEEN 157 AND 180
/

-- FACTURAS --

INSERT INTO CAB_FACTURA
    VALUES (1, TO_DATE('05/03/2019', 'DD/MM/YYYY'), 30, 5);

INSERT INTO CAB_FACTURA 
    VALUES (2, TO_DATE('02/01/2019', 'DD/MM/YYYY'), 15, 4);

INSERT INTO CAB_FACTURA
    VALUES (3, TO_DATE('20/02/2019', 'DD/MM/YYYY'), 90, 3);

INSERT INTO CAB_FACTURA
    VALUES (4, TO_DATE('05/03/2019', 'DD/MM/YYYY'), 90, 2);

INSERT INTO CAB_FACTURA
    VALUES (6, TO_DATE('05/01/2019', 'DD/MM/YYYY'), 30, 1);

INSERT INTO CAB_FACTURA
    VALUES (7, TO_DATE('03/11/2018', 'DD/MM/YYYY'), 30, 5);

INSERT INTO CAB_FACTURA
    VALUES (8, TO_DATE('19/02/2019', 'DD/MM/YYYY'), 90, 2);

INSERT INTO CAB_FACTURA
    VALUES (9, TO_DATE('28/02/2019', 'DD/MM/YYYY'), 15, 4);

INSERT INTO CAB_FACTURA
    VALUES (10, TO_DATE('20/02/2019', 'DD/MM/YYYY'), 15, 6);

-- CAB_ALBARAN

INSERT INTO CAB_ALBARAN(NUM_ALBARAN, FECHA_ALBARAN)
SELECT A.ALBARAN, A.FECHA_ALBARAN
FROM ALMANCEN1.ALBARANES A
/

-- FORMA_PAGO

INSERT INTO FORMA_PAGO(COD_PAGO, DESCRIPCION_FORMA_PAGO)
SELECT DECODE(F.FORMPAGO, 'C', '1', 'L1', '2' , 'L2', '3', 'L3', '5', 'L4', '6', 'NO PREVISTO'), F.DESCRIPCION
FROM ALMACEN1.FORMPAGOS F


INSERT INTO PAISES
    VALUES('ALDERNEY', 'LIBRA BRITANICA')
/

INSERT INTO PAISES
    VALUES('ALDERNEY', 'LIBRA DE ALDERNEY');

INSERT INTO PAISES
    VALUES('ALDERNEY', 'LIBRA DE GUERSNEY');

INSERT INTO PAISES
    VALUES('ANGOLA', 'KWANZA ANGOLEÑO');

INSERT INTO PAISES
    VALUES('ALEMANIA', 'EURO');

INSERT INTO PAISES
    VALUES('ANDORRA', 'EURO');

INSERT INTO PAISES
    VALUES('FRANCIA', 'EURO');

INSERT INTO PAISES
    VALUES('BELGICA', 'EURO');

INSERT INTO PAISES
    VALUES('GIBRALTAR', 'LIBRA ESTERLINA');

INSERT INTO PAISES
    VALUES('GIBRALTAR', 'EURO');

INSERT INTO PAISES
    VALUES('MARRUECOS', 'DIHRAM');

INSERT INTO PAISES
    VALUES('JAPON', 'YEN');

INSERT INTO PAISES
    VALUES('CHINA', 'YUAN');

INSERT INTO PAISES
    VALUES('TAILANDIA', 'BAHT');

INSERT INTO PAISES
    VALUES('ESTADOS UNIDOS', 'DOLAR');

INSERT INTO PAISES
    VALUES('ECUADOR', 'DOLAR');