/* esto es un ejemplo */

INSERT INTO PROVINCIAS(COD_PROVINCIA, PREFIJO_PROVINCIA, DESCRIPCION_PROVINCIA)
SELECT P.PROVINCIA, P.PREFIJO, P.DESCRIPCION
FROM ALMACEN1.PROVINCIAS P
WHERE P.PROVINCIA != 20 AND P.PROVINCIA != 28
/

INSERT INTO PROVEEDORES(COD_PROVEEDOR, NOMBRE_EMPRESA, DIRECCION, POBLACION, TELEFONO, COD_PROVINCIA)
SELECT P.PROVEEDOR, P.EMPRESA, P.DIRECCION1, P.POBLACION, P.TELEFONO, P.PROVINCIA
FROM ALMACEN1.PROVEEDORES P
WHERE P.PROVEEDOR != 127 AND P.PROVEEDOR != 148 AND P.PROVEEDOR != 101
/

INSERT INTO MEDIDAS(COD_UNIDAD_MEDIDA, DESCRIPCION_UNIDAD_MEDIDA)
SELECT DECODE(UPPER(U.UNIDAD), 'UN', TO_CHAR(1), 'M', TO_CHAR(2), 'CJ', TO_CHAR(4), 'L', TO_CHAR(5), 'CC', TO_CHAR(6), 'NO PREVISTO'), U.DESCRIPCION
FROM ALMACEN1.UNIDADES U
WHERE UPPER(U.UNIDAD) != 'KG'
/

INSERT INTO DESCUENTOS
VALUES('HABITUAL', 0)
/

/* falla por el check del stock */
INSERT INTO ARTICULOS(COD_ARTICULO, TIPO_ARTICULO, DESCRIPCION_ARTICULO, PRECIO_VENTA, STOCK, STOCK_MINIMO, COD_UNIDAD_MEDIDA)
SELECT ARTICULO, 'HABITUAL' TIPO, DESCRIPCION, PR_VENT, EXISTENCIAS, BAJO_MINIMO, DECODE(UPPER(UNIDAD), 'UN', '1', 'M', '2', 'CJ', '4', 'L', '5', 'CC', '6', 'KG', '7', 'NO PREVISTO')
FROM ALMACEN1.ARTICULOS
/
